# Generated by Django 4.2.5 on 2023-10-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0002_notice_alter_carousal_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_image', models.ImageField(upload_to='principal')),
                ('principal_quote', models.TextField()),
                ('chariman_image', models.ImageField(upload_to='chairman')),
                ('chairman_quote', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
