# Generated by Django 4.2.5 on 2023-10-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0003_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='chariman_image',
            new_name='chairman_image',
        ),
    ]
