# Generated by Django 4.2.5 on 2023-10-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0004_rename_chariman_image_quote_chairman_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('প্রতিষ্ঠান_পরিচিতি', models.FileField(upload_to='information')),
                ('পাঠদান_সংক্রান্ত', models.FileField(upload_to='information')),
                ('এমপিও_তথ্য', models.FileField(upload_to='information')),
                ('শিক্ষক_কর্মচারী', models.FileField(upload_to='information')),
                ('ব্যাবস্থাপনা_কমিটি', models.FileField(upload_to='information')),
                ('একাদশ_শ্রেণি_শিক্ষার্থী_তথ্য', models.FileField(upload_to='information')),
                ('দ্বাদশ_শ্রেণি_শিক্ষার্থী_তথ্য', models.FileField(upload_to='information')),
                ('ডিগ্রি_শিক্ষার্থী_তথ্য', models.FileField(upload_to='information')),
            ],
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='pdf',
            new_name='document',
        ),
    ]
