# Generated by Django 4.2.5 on 2023-10-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0006_rename_এক_দশ_শ_র_ণ__শ_ক_ষ_র_থ__তথ_য_information_degree_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(upload_to='photo_gallery')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='carousal',
            name='image',
            field=models.ImageField(upload_to='carousal'),
        ),
    ]
